"""Backend-agnostic surrogate core: the Prediction type and the Model fit/predict lifecycle."""

from pysurrogate.core.kernel import (
    ComposedKernel,
    Correlation,
    Cubic,
    CubicRadial,
    Exp,
    Exponential,
    Gaussian,
    GeneralizedExponential,
    Kernel,
    KPLSKernel,
    Linear,
    LinearRadial,
    Mahalanobis,
    Matern,
    Metric,
    Multiquadric,
    ProductKernel,
    Profile,
    ProjectedSquare,
    RadialKernel,
    RationalQuadratic,
    ReducedMetric,
    Spherical,
    Spline,
    SquareThenMix,
    ThinPlateSpline,
    WeightedAbs,
    WeightedSquare,
    calc_kernel_matrix,
    calc_kernel_tensor,
)
from pysurrogate.core.model import Model
from pysurrogate.core.optimizer import Callback, Evaluation, Optimizer, Problem, Result
from pysurrogate.core.parameter import Encoding, Log10, Parameter, ParameterSpace
from pysurrogate.core.partitioning import (
    DEFAULT_CV_FOLDS,
    CrossvalidationPartitioning,
    Partitioning,
    RandomPartitioning,
    Split,
    default_partitioning,
)
from pysurrogate.core.prediction import Prediction, predictions_frame
from pysurrogate.core.regression import (
    ConstantRegression,
    LinearRegression,
    QuadraticRegression,
    Regression,
)
from pysurrogate.core.sampling import LHS, Random, Sampling, SamplingMethod
from pysurrogate.core.transformation import (
    NoNormalization,
    Plog,
    Standardization,
    Transformation,
    ZeroToOneNormalization,
)

__all__ = [
    "Model",
    "Prediction",
    "predictions_frame",
    "Problem",
    "Optimizer",
    "Callback",
    "Evaluation",
    "Result",
    "Sampling",
    "SamplingMethod",
    "LHS",
    "Random",
    "Transformation",
    "NoNormalization",
    "Standardization",
    "ZeroToOneNormalization",
    "Plog",
    "Partitioning",
    "CrossvalidationPartitioning",
    "RandomPartitioning",
    "Split",
    "default_partitioning",
    "DEFAULT_CV_FOLDS",
    "Regression",
    "ConstantRegression",
    "LinearRegression",
    "QuadraticRegression",
    # kernel zoo (GP covariances + radial bases)
    "Kernel",
    "Correlation",
    "ProductKernel",
    "RadialKernel",
    "Gaussian",
    "Cubic",
    "Exponential",
    "Linear",
    "GeneralizedExponential",
    "Spline",
    "Spherical",
    "RationalQuadratic",
    "Matern",
    "ThinPlateSpline",
    "Multiquadric",
    "LinearRadial",
    "CubicRadial",
    # kernel composition (distance x curve) + reusable metrics/profiles
    "Metric",
    "Profile",
    "ComposedKernel",
    "ReducedMetric",
    "Exp",
    "WeightedSquare",
    "WeightedAbs",
    "ProjectedSquare",
    "SquareThenMix",
    "Mahalanobis",
    "KPLSKernel",
    "calc_kernel_matrix",
    "calc_kernel_tensor",
    # tunable-parameter concept
    "Parameter",
    "ParameterSpace",
    "Encoding",
    "Log10",
]
