"""Correlation kernels for Dace -- re-exported from the shared :mod:`pysurrogate.core.kernel`."""

from pysurrogate.core.kernel import (
    ComposedKernel,
    Correlation,
    Cubic,
    Exp,
    Exponential,
    Gaussian,
    GeneralizedExponential,
    Kernel,
    KPLSKernel,
    Linear,
    Mahalanobis,
    Matern,
    MaternProfile,
    Metric,
    ProductKernel,
    Profile,
    ProjectedSquare,
    RationalQuadratic,
    RationalQuadraticProfile,
    Spherical,
    Spline,
    SquareThenMix,
    WeightedAbs,
    WeightedSquare,
    calc_kernel_matrix,
    calc_kernel_tensor,
)

__all__ = [
    "Correlation",
    "Kernel",
    "ProductKernel",
    # distance x curve composition
    "Metric",
    "Profile",
    "ComposedKernel",
    "Exp",
    "RationalQuadraticProfile",
    "MaternProfile",
    "WeightedSquare",
    "WeightedAbs",
    "ProjectedSquare",
    "SquareThenMix",
    # concrete kernels
    "Gaussian",
    "Cubic",
    "Exponential",
    "Linear",
    "GeneralizedExponential",
    "Spline",
    "Spherical",
    "RationalQuadratic",
    "Matern",
    "KPLSKernel",
    "Mahalanobis",
    "calc_kernel_matrix",
    "calc_kernel_tensor",
]
