"""pysurrogate — a unified surrogate-modeling toolkit (sampling, fitting, selection)."""

from pysurrogate.core import (
    LHS,
    Callback,
    CrossvalidationPartitioning,
    Evaluation,
    Model,
    NoNormalization,
    Optimizer,
    Partitioning,
    Plog,
    Prediction,
    Problem,
    Random,
    RandomPartitioning,
    Result,
    Sampling,
    SamplingMethod,
    Split,
    Standardization,
    Transformation,
    ZeroToOneNormalization,
    predictions_frame,
)
from pysurrogate.core.kernel import (
    ComposedKernel,
    Cubic,
    CubicRadial,
    Exp,
    Exponential,
    Gaussian,
    GeneralizedExponential,
    Kernel,
    KPLSKernel,
    LinearRadial,
    Mahalanobis,
    Matern,
    Metric,
    Multiquadric,
    ProductKernel,
    Profile,
    ProjectedSquare,
    RadialKernel,
    RationalQuadratic,
    ReducedMetric,
    Spherical,
    Spline,
    SquareThenMix,
    ThinPlateSpline,
    WeightedAbs,
    WeightedSquare,
)
from pysurrogate.core.parameter import Encoding, Log10, Parameter, ParameterSpace
from pysurrogate.core.regression import (
    ConstantRegression,
    LinearRegression,
    QuadraticRegression,
    Regression,
)
from pysurrogate.dace import MAP, Dace, HeldOut, MaximumLikelihood, Selection
from pysurrogate.landscape import Landscape
from pysurrogate.models import (
    KNN,
    KPLS,
    RBF,
    SVR,
    DeepKernelGP,
    InverseDistanceWeighting,
    Kriging,
    PolynomialRegression,
    RandomForest,
    RotatedKriging,
    SimpleMean,
    active_subspace,
)
from pysurrogate.optimizer import LBFGS, Adam, Boxmin, PatternSearch, Restart
from pysurrogate.selection import (
    AutoModel,
    Benchmark,
    FunctionBenchmark,
    StudyResult,
    as_named,
    cartesian,
    score,
    study,
)

__version__ = "0.1.0"

__all__ = [
    # core surrogate lifecycle
    "Model",
    "Prediction",
    "predictions_frame",
    # the flagship surrogate
    "Dace",
    # hyperparameter-selection strategies
    "Selection",
    "MaximumLikelihood",
    "MAP",
    "HeldOut",
    # kernel zoo (GP covariances + radial bases)
    "Kernel",
    "Gaussian",
    "Exponential",
    "Matern",
    "RationalQuadratic",
    "GeneralizedExponential",
    "Cubic",
    "Spline",
    "Spherical",
    "ThinPlateSpline",
    "Multiquadric",
    "LinearRadial",
    "CubicRadial",
    # kernel composition (distance x curve) + reusable metrics/profiles
    "Metric",
    "Profile",
    "ComposedKernel",
    "ProductKernel",
    "RadialKernel",
    "ReducedMetric",
    "Exp",
    "WeightedSquare",
    "WeightedAbs",
    "ProjectedSquare",
    "SquareThenMix",
    "Mahalanobis",
    "KPLSKernel",
    # regression trend bases
    "Regression",
    "ConstantRegression",
    "LinearRegression",
    "QuadraticRegression",
    # tunable-parameter concept
    "Parameter",
    "ParameterSpace",
    "Encoding",
    "Log10",
    # model backends
    "Kriging",
    "KPLS",
    "RotatedKriging",
    "DeepKernelGP",
    "active_subspace",
    "RBF",
    "SVR",
    "KNN",
    "InverseDistanceWeighting",
    "SimpleMean",
    "PolynomialRegression",
    "RandomForest",
    # generic optimizer layer
    "Problem",
    "Optimizer",
    "Callback",
    "Evaluation",
    "Result",
    "LBFGS",
    "PatternSearch",
    "Boxmin",
    "Adam",
    "Restart",
    # sampling
    "Sampling",
    "SamplingMethod",
    "LHS",
    "Random",
    # input/output transformations
    "Transformation",
    "NoNormalization",
    "Standardization",
    "ZeroToOneNormalization",
    "Plog",
    # partitioning / cross-validation
    "Partitioning",
    "CrossvalidationPartitioning",
    "RandomPartitioning",
    "Split",
    # benchmarking & selection front-ends
    "Benchmark",
    "AutoModel",
    "FunctionBenchmark",
    "study",
    "StudyResult",
    "score",
    "cartesian",
    "as_named",
    # exploratory landscape analysis
    "Landscape",
    "__version__",
]
